### ISSUE TITLE
Newlines are not rendered in profile description 

### ISSUE THREAD

**Issue by humble-GOAT** [Pleb5/satshoot#32]
I found an issue on the profile screen - it's not rendering newlines.

For example on snort.social my profile looks like this:

![image](https://github.com/user-attachments/assets/8c5c1904-7f92-48d5-8a88-046a3fc5a061)

However, on satshoot it looks like this:

![image](https://github.com/user-attachments/assets/13f92eee-080b-4b74-b76c-8efde91e0b4e)

**Comment by Pleb5** [comment]
This could be attached to #14

**Comment by Pleb5** [comment]
This is resolved in 0.1.1
