### ISSUE TITLE
Use proper relays when handling Cashu wallet and Nutzaps

### ISSUE THREAD

**Issue by Pleb5** [Pleb5/satshoot#51]
- Publish Wallet event (37375) updates to ONLY user-defined relays coming from the wallet event itself. When user creates new Wallet just use the default relays assigned to new Wallet event
- Publish **Token events**(7375) and **History events**(7376) the same way as Wallet event 
- Publish **Cashu Mint List**(10019) event everywhere possible (like metadata). Utilize ndk.useTemporaryRelay() fn with blastrUrl before publishing
- Publish **NutZaps**(9321) to **recipients read-relays**(ndk takes care of this) AND **specified relays** taken from his CashuMintList(10019) event (add these relays temporarily in a for loop along with ndk.useTemporaryRelay() )

**Comment by Pleb5** [comment]
Could be the solution to #53 and #55

**Comment by ghost** [comment]
NDK is handling first two points and next 2 points resolved in  #62
