### ISSUE TITLE
“Work” and “Feedback” buttons not highlighted when active

### ISSUE THREAD

**Issue by humble-GOAT** [Pleb5/satshoot#72]
![image](https://github.com/user-attachments/assets/7a022347-d96f-4be4-8953-a59c23d53d0b)

**Comment by Pleb5** [comment]
This is because this feature only pops up modals which are in the foreground only as long as user interacts with them.
After they are closed and the drawer is closed as well. The highlight therefore is only necessary when you are on a _page_, not when viewing a modal
